project_name: cloud-backend

before:
  hooks:
    - go mod tidy

builds:
  - main: ./main.go
    binary: cloud-backend
    ldflags:
      - -s -w -X github.com/hyper-tuner/cloud-backend.Version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm
