version: '3.1'

services:
  cloud-backend:
    platform: linux/x86_64
    build: .
    restart: unless-stopped
    command: ["/cloud-backend", "serve", "--http=0.0.0.0:8080"]
    volumes:
      - ./pb_data:/pb_data
    ports:
      - 80:8080
