FROM alpine:latest

ARG VERSION=1.1.1

ADD https://github.com/hyper-tuner/cloud-backend/releases/download/v${VERSION}/cloud-backend_${VERSION}_linux_amd64.tar.gz /tmp/cloud-backend

RUN tar -zxf /tmp/cloud-backend
